

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "MainPage.xaml.h"




void ::App4::MainPage::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///MainPage.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///MainPage.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the TextBox named 'search_box'
    search_box = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"search_box"));
    // Get the Button named 'Search_button'
    Search_button = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Search_button"));
    // Get the TextBlock named 'State_Name'
    State_Name = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_Name"));
    // Get the TextBlock named 'OS_frequency'
    OS_frequency = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"OS_frequency"));
    // Get the TextBlock named 'OS_LTS'
    OS_LTS = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"OS_LTS"));
    // Get the TextBlock named 'OS_TTS'
    OS_TTS = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"OS_TTS"));
    // Get the TextBlock named 'ST_frequency'
    ST_frequency = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ST_frequency"));
    // Get the Button named 'State_20'
    State_20 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_20"));
    // Get the Ellipse named 'State_5'
    State_5 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_5"));
    // Get the Ellipse named 'State_45'
    State_45 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_45"));
    // Get the Ellipse named 'State_35'
    State_35 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_35"));
    // Get the Ellipse named 'State_29'
    State_29 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_29"));
    // Get the Ellipse named 'State_2'
    State_2 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_2"));
    // Get the Ellipse named 'State_42'
    State_42 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_42"));
    // Get the Ellipse named 'State_26'
    State_26 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_26"));
    // Get the Ellipse named 'State_32'
    State_32 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_32"));
    // Get the Ellipse named 'State_4'
    State_4 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_4"));
    // Get the Ellipse named 'State_11'
    State_11 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_11"));
    // Get the Ellipse named 'State_41'
    State_41 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_41"));
    // Get the Ellipse named 'State_15'
    State_15 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_15"));
    // Get the Ellipse named 'State_39'
    State_39 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_39"));
    // Get the Ellipse named 'State_48'
    State_48 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_48"));
    // Get the Ellipse named 'State_24'
    State_24 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_24"));
    // Get the Ellipse named 'State_22'
    State_22 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_22"));
    // Get the Ellipse named 'State_3'
    State_3 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_3"));
    // Get the Ellipse named 'State_23'
    State_23 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_23"));
    // Get the Ellipse named 'State_21'
    State_21 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_21"));
    // Get the Ellipse named 'State_14'
    State_14 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_14"));
    // Get the Ellipse named 'State_25'
    State_25 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_25"));
    // Get the Ellipse named 'State_47'
    State_47 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_47"));
    // Get the Ellipse named 'State_12'
    State_12 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_12"));
    // Get the Ellipse named 'State_16'
    State_16 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_16"));
    // Get the Ellipse named 'State_30'
    State_30 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_30"));
    // Get the Ellipse named 'State_40'
    State_40 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_40"));
    // Get the Ellipse named 'State_38'
    State_38 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_38"));
    // Get the Ellipse named 'State_44'
    State_44 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_44"));
    // Get the Ellipse named 'State_33'
    State_33 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_33"));
    // Get the Ellipse named 'State_36'
    State_36 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_36"));
    // Get the Ellipse named 'State_18'
    State_18 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_18"));
    // Get the Ellipse named 'State_9'
    State_9 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_9"));
    // Get the Ellipse named 'State_43'
    State_43 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_43"));
    // Get the Ellipse named 'State_31'
    State_31 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_31"));
    // Get the Ellipse named 'State_8'
    State_8 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_8"));
    // Get the Ellipse named 'State_19'
    State_19 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_19"));
    // Get the Ellipse named 'State_46'
    State_46 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_46"));
    // Get the Ellipse named 'State_0'
    State_0 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_0"));
    // Get the Ellipse named 'State_13'
    State_13 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_13"));
    // Get the Ellipse named 'State_17'
    State_17 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_17"));
    // Get the Ellipse named 'State_34'
    State_34 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_34"));
    // Get the Ellipse named 'State_49'
    State_49 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_49"));
    // Get the Ellipse named 'State_1'
    State_1 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_1"));
    // Get the Ellipse named 'State_7'
    State_7 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_7"));
    // Get the Ellipse named 'State_27'
    State_27 = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_27"));
    // Get the Ellipse named 'State_20New'
    State_20New = safe_cast<::Windows::UI::Xaml::Shapes::Ellipse^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"State_20New"));
}

void ::App4::MainPage::Connect(int connectionId, Platform::Object^ target)
{
    switch (connectionId)
    {
    case 1:
        (safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(target))->SelectionChanged +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::TextBlock_SelectionChanged);
        break;
    case 2:
        (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(target))->TextChanged +=
            ref new ::Windows::UI::Xaml::Controls::TextChangedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Controls::TextChangedEventArgs^))&MainPage::TextBox_TextChanged);
        break;
    case 3:
        (safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(target))->SelectionChanged +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::TextBlock_SelectionChanged_1);
        break;
    case 4:
        (safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(target))->SelectionChanged +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::TextBlock_SelectionChanged);
        break;
    case 5:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Button_Click);
        break;
    case 6:
        (safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(target))->SelectionChanged +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::TextBlock_SelectionChanged_2);
        break;
    case 7:
        (safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(target))->SelectionChanged +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::TextBlock_SelectionChanged_2);
        break;
    case 8:
        (safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(target))->SelectionChanged +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::TextBlock_SelectionChanged_2);
        break;
    case 9:
        (safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(target))->SelectionChanged +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::TextBlock_SelectionChanged_2);
        break;
    case 10:
        (safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(target))->SelectionChanged +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::TextBlock_SelectionChanged_2);
        break;
    case 11:
        (safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(target))->SelectionChanged +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::TextBlock_SelectionChanged_2);
        break;
    case 12:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_5_DoubleTapped);
        break;
    case 13:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_45_DoubleTapped);
        break;
    case 14:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_35_DoubleTapped);
        break;
    case 15:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_29_DoubleTapped);
        break;
    case 16:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_2_DoubleTapped);
        break;
    case 17:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_42_DoubleTapped);
        break;
    case 18:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_26_DoubleTapped);
        break;
    case 19:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_32_DoubleTapped);
        break;
    case 20:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_4_DoubleTapped);
        break;
    case 21:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_11_DoubleTapped);
        break;
    case 22:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_41_DoubleTapped);
        break;
    case 23:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_15_DoubleTapped);
        break;
    case 24:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_39_DoubleTapped);
        break;
    case 25:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_48_DoubleTapped);
        break;
    case 26:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_24_DoubleTapped);
        break;
    case 27:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_22_DoubleTapped);
        break;
    case 28:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_3_DoubleTapped);
        break;
    case 29:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_23_DoubleTapped);
        break;
    case 30:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_21_DoubleTapped);
        break;
    case 31:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_14_DoubleTapped);
        break;
    case 32:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_25_DoubleTapped);
        break;
    case 33:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_47_DoubleTapped);
        break;
    case 34:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_12_DoubleTapped);
        break;
    case 35:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_16_DoubleTapped);
        break;
    case 36:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_30_DoubleTapped);
        break;
    case 37:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_40_DoubleTapped);
        break;
    case 38:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_38_DoubleTapped);
        break;
    case 39:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_44_DoubleTapped);
        break;
    case 40:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_33_DoubleTapped);
        break;
    case 41:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_36_DoubleTapped);
        break;
    case 42:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_18_DoubleTapped);
        break;
    case 43:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_9_DoubleTapped);
        break;
    case 44:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_43_DoubleTapped);
        break;
    case 45:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_31_DoubleTapped);
        break;
    case 46:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_8_DoubleTapped);
        break;
    case 47:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_19_DoubleTapped);
        break;
    case 48:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_46_DoubleTapped);
        break;
    case 49:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_0_DoubleTapped);
        break;
    case 50:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_13_DoubleTapped);
        break;
    case 51:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_17_DoubleTapped);
        break;
    case 52:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_34_DoubleTapped);
        break;
    case 53:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        break;
    case 54:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_1_DoubleTapped);
        break;
    case 55:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_7_DoubleTapped);
        break;
    case 56:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_27_DoubleTapped);
        break;
    case 57:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->DataContextChanged +=
            ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Windows::UI::Xaml::DataContextChangedEventArgs^>(this, (void (::App4::MainPage::*)(Windows::UI::Xaml::FrameworkElement^, Windows::UI::Xaml::DataContextChangedEventArgs^))&MainPage::State_5_DataContextChanged);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App4::MainPage::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::State_20New_DoubleTapped);
        break;
    }
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

