

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class TextBox;
                ref class Button;
                ref class TextBlock;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Shapes {
                ref class Ellipse;
            }
        }
    }
}

namespace App4
{
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::TextBox^ search_box;
        private: ::Windows::UI::Xaml::Controls::Button^ Search_button;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ State_Name;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ OS_frequency;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ OS_LTS;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ OS_TTS;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ ST_frequency;
        private: ::Windows::UI::Xaml::Controls::Button^ State_20;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_5;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_45;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_35;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_29;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_2;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_42;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_26;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_32;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_4;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_11;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_41;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_15;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_39;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_48;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_24;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_22;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_3;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_23;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_21;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_14;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_25;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_47;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_12;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_16;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_30;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_40;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_38;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_44;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_33;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_36;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_18;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_9;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_43;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_31;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_8;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_19;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_46;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_0;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_13;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_17;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_34;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_49;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_1;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_7;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_27;
        private: ::Windows::UI::Xaml::Shapes::Ellipse^ State_20New;
    };
}

